import {
  Brain02Icon,
  CodeCircleIcon,
  RoboticIcon,
  StarsIcon,
  CodeFolderIcon,
  AudioBook01Icon,
  Database01Icon,
} from "@hugeicons/react";
export const categories = [
  {
    name: "Artificial Intelligence",
    icon: Brain02Icon,
    iconProps: { variant: "bulk", size: 24 },
    className: "border-[#FFD03B] text-[#FFD03B]",
    color: "#FFD03B",
  },
  {
    name: "Programming",
    icon: CodeCircleIcon,
    iconProps: { variant: "stroke", size: 24 },
    className: "border-[#68D8FC] text-[#68D8FC]",
    color: "#68D8FC",
  },
  {
    name: "Machine learning",
    icon: RoboticIcon,
    iconProps: { variant: "duotone", size: 24 },
    className: "border-[#22C55E] text-[#22C55E]",
    color: "#22C55E",
  },
  {
    name: "AI Tools",
    icon: StarsIcon,
    iconProps: { variant: "bulk", size: 24 },
    className: "border-[#CC48F4] text-[#CC48F4]",
    color: "#CC48F4",
  },
  {
    name: "Software Development",
    icon: CodeFolderIcon,
    iconProps: { variant: "bulk", size: 24 },
    className: "border-[#F0493E] text-[#F0493E]",
    color: "#F0493E",
  },
  {
    name: "AI Know How’s",
    icon: AudioBook01Icon,
    iconProps: { variant: "bulk", size: 24 },
    className: "border-[#6068F4] text-[#6068F4]",
    color: "#6068F4",
  },
  {
    name: "Data Science",
    icon: Database01Icon,
    iconProps: { variant: "bulk", size: 24 },
    className: "border-[#CC48F4] text-[#CC48F4]",
    color: "#CC48F4",
  },
];
