import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import { Montserrat_Alternates, Manrope } from "next/font/google";

const montserratAlt = Montserrat_Alternates({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat-alt",
});
const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlt.variable} ${manrope.variable} antialiased`}
      >
        {/* <Header /> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
