import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "../components/Navbar";
import { Montserrat_Alternates, Manrope, Golos_Text } from "next/font/google";
import { FloatingNavDemo } from "../components/Nav";
import localFont from "next/font/local";
import Footer from "../components/Footer";

const montserratAlt = Montserrat_Alternates({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat-alt",
});
const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});
const golosText = Golos_Text({
  weight: ["400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-golos-text",
});
const ovSoge = localFont({
  src: [
    {
      path: "./fonts/OVSoge-Light.otf",
      weight: "300", // Light weight
    },
    {
      path: "./fonts/OVSoge-Regular.otf",
      weight: "400", // Regular weight
    },
    {
      path: "./fonts/OVSoge-Medium.otf",
      weight: "500", // Regular weight
    },
    {
      path: "./fonts/OVSoge-SemiBold.otf",
      weight: "600", // Regular weight
    },
    {
      path: "./fonts/OVSoge-Bold.otf",
      weight: "700", // Bold weight
    },
    {
      path: "./fonts/OVSoge-Black.otf",
      weight: "900", // Black weight (extra bold)
    },
  ],
  variable: "--font-ov-soge",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratAlt.variable} ${manrope.variable} ${ovSoge.variable} ${golosText.variable} antialiased`}
      >
        {/* <Header /> */}
        {/* <Navbar /> */}

        {children}
      </body>
    </html>
  );
}
